<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</title>
<style type="text/css"> <?php include('assets/css/formaja.css') ?> </style>
<style type="text/javascript"> <?php include('assets/js/formaja.js') ?> </style>

     <!-- core CSS -->
    <link href="<?php echo base_url();?>assets/css/bootstrap.min.css" rel="stylesheet">
  <style type="text/css"><?php include('assets/css/ayokerja.css') ?></style>

</head>


<body>

	<!--<img id="top" src="top.png" alt=""> -->
	<div id="form_container">
		<div id="container">
		<!--h1><a>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</a></h1-->

		<?php // echo form_open('Con_pendaftar/tambahpendaftar'); ?>
		<form id="form_1049697" class="appnitro"  method="post" action="">
		<div class="form_description" align="center">
			<h3>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</h3>
			<p>JL. WARDOYO NO 12 blk KOMP. TNI-AL KENJERAN SURABAYA</p>
		</div>
<?php
												 //var_dump($pendaftar).'</br>';		?>

		</div>

		<div id="container">
			<ul >





		
			<h3>C. KESEHATAN ANAK</h3>
			<p></p>
		


		<a align="text-right" href="kelainan" class="btn btn-primary btn-lg" role="button" >Isi data kelainan tubuh</a></span> 
		<br>
		<br>
		<a align="text-right" href="imunisasi" class="btn btn-primary btn-lg" role="button" >Isi data imunisasi</a></span> 
		<br>
		<br>
		<a align="text-right" href="saudara" class="btn btn-primary btn-lg" role="button" >Lanjutkan</a></span> 


			</ul>


		</div>
		</form>
		<!--div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div-->
	</div>
	<!--img id="bottom" src="bottom.png" alt=""-->
	</body>
</html>
