<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</title>
<style type="text/css"> <?php include('assets/css/formaja.css') ?> </style>
<style type="text/javascript"> <?php include('assets/js/formaja.js') ?> </style>

     <!-- core CSS -->
    <link href="<?php echo base_url();?>assets/css/bootstrap.min.css" rel="stylesheet">
  <style type="text/css"><?php include('assets/css/ayokerja.css') ?></style>

</head>


<body>

	<!--<img id="top" src="top.png" alt=""> -->
	<div id="form_container">
		<div id="container">
		<!--h1><a>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</a></h1-->

		<?php //echo form_open('Con_pendaftar/tambahpendaftar'); ?>
		<form id="form_1049697" class="appnitro"  method="post" action="">
		<div class="form_description" align="center">
			<h3>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</h3>
			<p>JL. WARDOYO NO 12 blk KOMP. TNI-AL KENJERAN SURABAYA</p>
		</div>

		</div>

		<div id="container">
			<ul >



		<!--li class="section_break">
			masih gajelas, skip aja gpp,tp sepertinya ke ciri_fisik
			-->
			<h3>E. CIRI KHAS ANAK</h3>
			<p></p>
		


				



		<li id="li_45" >

		<div>
			<!--<input id="element_45" name="siswa_ciri" class="element text medium" type="text" maxlength="255" value=""/>-->
		<?php echo form_input('siswa_ciri'); ?>
		</div>
		</li>
		masukkan ke dalam tabel ciri_kepribadian
		<li id="li_74" >
		<label class="description" for="siswa_kepribadian">2. Ciri kepribadian yang menonjol </label>
		<span>
			<input id="element_74_1" name="siswa_kepribadian" class="element radio" type="radio" value="1" />
<label class="choice" for="element_74_1">Periang</label>
<input id="element_74_2" name="siswa_kepribadian" class="element radio" type="radio" value="2" />
<label class="choice" for="element_74_2">Pemalu</label>
<input id="element_74_3" name="siswa_kepribadian" class="element radio" type="radio" value="3" />
<label class="choice" for="element_74_3">suka menyendiri</label>
<input id="element_74_4" name="siswa_kepribadian" class="element radio" type="radio" value="4" />
<label class="choice" for="element_74_4">mudah bergaul</label>
<input id="element_74_5" name="siswa_kepribadian" class="element radio" type="radio" value="5" />
<label class="choice" for="element_74_5">aktif</label>
<input id="element_74_6" name="siswa_kepribadian" class="element radio" type="radio" value="6" />
<label class="choice" for="element_74_6">pendiam</label>
<input id="element_74_7" name="siswa_kepribadian" class="element radio" type="radio" value="7" />
<label class="choice" for="element_74_7">pemarah</label>
<input id="element_74_8" name="siswa_kepribadian" class="element radio" type="radio" value="8" />
<label class="choice" for="element_74_8">lain - lain</label>

		</span>
		</li>		<li id="li_54" >
		<label class="description" for="element_54"> </label>
		<div>
			<input id="element_54" name="element_54" class="element text medium" type="text" maxlength="255" value=""/>
		</div>
		</li>		<li id="li_55" >
		<label class="description" for="siswa_bakat">3. Bakat khusus yang menonjol </label>
		<div>
			<?php echo form_input('siswa_bakat'); ?>
		</div>
		</li>		<li id="li_56" >
		<label class="description" for="element_56">4. Prestasi yang pernah diraih </label>
		<div>
			<?php echo form_input('siswa_prestasi'); ?>
		</div>
		</li>	


		<br>
		<a align="text-right" href="wali" class="btn btn-primary btn-lg" role="button" >Lanjutkan</a></span> 





			</ul>


		</div>
		</form>
		<!--div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div-->
	</div>
	<!--img id="bottom" src="bottom.png" alt=""-->
	</body>
</html>
