
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</title>
<style type="text/css"> <?php include('assets/css/formaja.css') ?> </style>
<style type="text/javascript"> <?php include('assets/js/formaja.js') ?> </style>

     <!-- core CSS -->
    <link href="<?php echo base_url();?>assets/css/bootstrap.min.css" rel="stylesheet">
  <style type="text/css"><?php include('assets/css/ayokerja.css') ?></style>

</head>


<body>

	<!--<img id="top" src="top.png" alt=""> -->
	<div id="form_container">
		<div id="container">
		<!--h1><a>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</a></h1-->
		
		<form id="form_1049697" class="appnitro"  method="post" action="">
		<div class="form_description" align="center">
			<h3>FORMULIR PENDAFTARAN SLB B-C OPTIMAL</h3>
			<p>JL. WARDOYO NO 12 blk KOMP. TNI-AL KENJERAN SURABAYA</p>
		</div>
<?php
                    var_dump($pendaftar['state']).'</br>';
		?>
		
		</div>

		<div id="container">
			<ul >

					<li class="section_break">
			<h3>Saya yang bertanda tangan dibawah ini:</h3>
			
		</li>		<li id="li_1" >
		<label class="description" for="element_1">Nama pendaftar </label>
		<div>
			<?php echo form_input('pendaftar_nama'); ?>
			

		</div>
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Status pendaftar terhadap anak </label>
		<div>
			<?php echo form_input('pendaftar_status'); ?>
		</div>
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Alamat rumah </label>
		<div>
			<?php echo form_input('pendaftar_rumah'); ?>
		</div>
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Telepon / HP </label>
		<div>
			<?php echo form_input('pendaftar_telepon'); ?>
		</div>
		</li>		

		<br>
	
		<input type="submit" name="submit" value="submit" class="btn btn-primary btn-lg" role="button" >Lanjutkan</input></span>	
		</form>



					<!--li class="buttons">
			    <input type="hidden" name="form_id" value="1049697" />

				<input id="saveForm" class="button_text" type="submit" name="submit" value="Lanjutkan" />
		</li>
			</ul-->


		</div>
		</form>
		<!--div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div-->
	</div>
	<!--img id="bottom" src="bottom.png" alt=""-->
	</body>
</html>
